Repository Turbotard/Symfony-Project, pull requests merged in 2023-09, with the labels that each got.

#3 Creation tables
  .env
  .idea/codeception.xml
  .idea/php.xml
  .idea/phpspec.xml
  .idea/phpunit.xml
  .idea/vcs.xml
  .idea/workspace.xml
  bin/console
  composer.json
  composer.lock
  src/Entity/Activities.php
  src/Entity/FriendGroup.php
  src/Entity/Users.php
  src/Repository/ActivitiesRepository.php
  src/Repository/FriendGroupRepository.php
  src/Repository/UsersRepository.php
Labels: BDD

#12 all forms
  config/routes.yaml
  src/Controller/ActivitiesController.php
  src/Controller/FriendGroupController.php
  src/Entity/Activities.php
  src/Entity/FriendGroup.php
  src/Entity/Users.php
  src/Form/ActivitiesType.php
  src/Form/FriendGroupType.php
  src/Form/UsersType.php
  templates/activities/_delete_form.html.twig
  templates/activities/_form.html.twig
  templates/activities/edit.html.twig
  templates/activities/index.html.twig
  templates/activities/new.html.twig
  templates/activities/show.html.twig
  templates/friend_group/_delete_form.html.twig
  templates/friend_group/_form.html.twig
  templates/friend_group/edit.html.twig
  templates/friend_group/index.html.twig
  templates/friend_group/new.html.twig
  templates/friend_group/show.html.twig
Labels: enhancement, BDD

#17 balance
  src/Controller/CalculController.php
  src/Services/CalculBalanceServices.php
  templates/calcul/index.html.twig
Labels: enhancement

#21 Security
  config/packages/security.yaml
  src/Controller/SecurityController.php
  src/Entity/Users.php
  src/Services/CalculBalanceServices.php
  templates/security/login.html.twig
  templates/users/index.html.twig
Labels: enhancement

#23 Security
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  src/Controller/CalculController.php
  src/Controller/RegistrationController.php
  src/Controller/UsersController.php
  src/Entity/Activities.php
  src/Entity/FriendGroup.php
  src/Entity/User.php
  src/Entity/Users.php
  src/Form/ActivitiesType.php
  src/Form/FriendGroupType.php
  src/Form/RegistrationFormType.php
  src/Form/RegistrationType.php
  src/Form/UsersType.php
  src/Repository/UserRepository.php
  src/Security/EmailVerifier.php
  src/Services/AddUserServices.php
  src/Services/CalculBalanceServices.php
  src/Services/PasswordAuthenticatedUserInterface.php
  symfony.lock
  templates/home/index.html.twig
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
Labels: enhancement
